"""004_agent_memory

Revision ID: 8198b7455b82
Revises: e13f55a1245f
Create Date: 2026-07-24 19:28:45.858856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8198b7455b82'
down_revision: Union[str, Sequence[str], None] = 'e13f55a1245f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'agent_memories',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('patient_id', sa.UUID(as_uuid=True), nullable=True),
        sa.Column('agent_name', sa.String(), nullable=True),
        sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_agent_name'), 'agent_memories', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_memories_id'), 'agent_memories', ['id'], unique=False)
    op.create_index(op.f('ix_agent_memories_patient_id'), 'agent_memories', ['patient_id'], unique=False)
    
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.UUID(as_uuid=True), nullable=True),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_memories_patient_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_agent_name'), table_name='agent_memories')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
