"""006_patient_documents

Revision ID: 83d87644772e
Revises: 
Create Date: 2026-07-24 20:28:32.155387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d87644772e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'patient_documents',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('patient_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('uploaded_by', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('storage_path', sa.String(), nullable=False),
        sa.Column('mime_type', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('document_type', sa.Enum('LAB_REPORT', 'PRESCRIPTION', 'DISCHARGE_SUMMARY', 'CLINICAL_NOTE', 'IMAGING_REPORT', 'OTHER', name='documenttypeenum'), nullable=False),
        sa.Column('processing_status', sa.Enum('UPLOADED', 'VALIDATING', 'PARSING', 'OCR_RUNNING', 'CHUNKING', 'EMBEDDING', 'LLM_EXTRACTION', 'FHIR_VALIDATION', 'ONTOLOGY_MAPPING', 'COMPLETED', 'FAILED_VALIDATION', 'FAILED_PARSING', 'FAILED_OCR', 'FAILED_LLM', 'FAILED_FHIR', name='processingstatusenum'), nullable=False),
        sa.Column('page_count', sa.Integer(), nullable=True),
        sa.Column('language', sa.String(), nullable=True),
        sa.Column('checksum', sa.String(), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('workflow_id', sa.String(), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_documents_checksum'), 'patient_documents', ['checksum'], unique=True)
    op.create_index(op.f('ix_patient_documents_id'), 'patient_documents', ['id'], unique=False)
    op.create_index(op.f('ix_patient_documents_patient_id'), 'patient_documents', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_documents_patient_id'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_id'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_checksum'), table_name='patient_documents')
    op.drop_table('patient_documents')
    op.execute('DROP TYPE documenttypeenum;')
    op.execute('DROP TYPE processingstatusenum;')
    # ### end Alembic commands ###
