"""002_fhir_tables

Revision ID: ce5913f1a75f
Revises: ba857ee0620e
Create Date: 2026-07-24 19:28:44.312227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5913f1a75f'
down_revision: Union[str, Sequence[str], None] = 'ba857ee0620e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'patients',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('fhir_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('gender', sa.String(), nullable=True),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('fhir_resource', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_fhir_id'), 'patients', ['fhir_id'], unique=True)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    
    op.create_table(
        'conditions',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('patient_id', sa.UUID(as_uuid=True), nullable=True),
        sa.Column('system', sa.String(), nullable=True),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('display', sa.String(), nullable=True),
        sa.Column('recorded_date', sa.DateTime(), nullable=True),
        sa.Column('fhir_resource', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    
    op.create_table(
        'observations',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('patient_id', sa.UUID(as_uuid=True), nullable=True),
        sa.Column('system', sa.String(), nullable=True),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('display', sa.String(), nullable=True),
        sa.Column('value_quantity', sa.JSON(), nullable=True),
        sa.Column('effective_datetime', sa.DateTime(), nullable=True),
        sa.Column('fhir_resource', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_fhir_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
