"""003_pgvector

Revision ID: e13f55a1245f
Revises: ce5913f1a75f
Create Date: 2026-07-24 19:28:44.984085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13f55a1245f'
down_revision: Union[str, Sequence[str], None] = 'ce5913f1a75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
